# Generated by Django 2.2.10 on 2020-08-24 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.CreateModel(
            name='SinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_number', models.CharField(max_length=1000)),
                ('schedule_number', models.CharField(max_length=1000, null=True)),
                ('special_item_number', models.CharField(max_length=1000, null=True)),
                ('sin_group_title', models.CharField(max_length=1000, null=True)),
                ('sin_description1', models.TextField(null=True)),
                ('sin_description2', models.TextField(null=True)),
                ('sin_order', models.CharField(max_length=1000, null=True)),
                ('co_fname', models.CharField(max_length=1000, null=True)),
                ('co_lname', models.CharField(max_length=1000, null=True)),
                ('co_phone', models.CharField(max_length=1000, null=True)),
                ('co_email', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_number', models.CharField(max_length=1000)),
                ('sin_group_title', models.CharField(max_length=1000, null=True)),
                ('sin_description1', models.CharField(max_length=1000, null=True)),
                ('sinMap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SinData')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('sin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sin')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audit_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('sin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
