# Generated by Django 2.2.10 on 2020-07-29 16:09

from django.db import migrations
from ..db_init import init_status, init_sindata

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_model_change_2')
    ]

    operations = [
        migrations.RunPython(init_status),
        migrations.RunPython(init_sindata)
    ]
