# Generated by Django 2.2.10 on 2020-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='audit_log',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='audit_log',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
