# Generated by Django 2.2.10 on 2020-08-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_model_change_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_number', models.CharField(max_length=1000)),
                ('schedule_number', models.CharField(max_length=1000, null=True)),
                ('special_item_number', models.CharField(max_length=1000, null=True)),
                ('sin_group_title', models.CharField(max_length=1000, null=True)),
                ('sin_description1', models.CharField(max_length=1000, null=True)),
                ('sin_description2', models.CharField(max_length=1000, null=True)),
                ('sin_order', models.CharField(max_length=1000, null=True)),
                ('co_fname', models.CharField(max_length=1000, null=True)),
                ('co_lname', models.CharField(max_length=1000, null=True)),
                ('co_phone', models.CharField(max_length=1000, null=True)),
                ('co_email', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sin',
            name='co_email',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='co_fname',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='co_lname',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='co_phone',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='schedule_number',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='sin_description1',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='sin_description2',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='sin_group_title',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='sin_number',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='sin_order',
        ),
        migrations.RemoveField(
            model_name='sin',
            name='special_item_number',
        ),
        migrations.AddField(
            model_name='sin',
            name='sinMap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SinData'),
        ),
    ]
