# Generated by Django 2.2.10 on 2020-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sin',
            name='co_email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='co_fname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='co_lname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='co_phone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='schedule_number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='sin_description1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='sin_description2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='sin_group_title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='sin_order',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sin',
            name='special_item_number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sin',
            name='sin_number',
            field=models.CharField(max_length=1000),
        ),
    ]
