# Generated by Django 2.2.10 on 2020-08-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_model_change_1'),
        ('api', '0002_status')
    ]

    operations = [
    ]
