# Generated by Django 2.2.10 on 2020-08-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindata',
            name='sin_description1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sindata',
            name='sin_description2',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
