version: "3.8"
services:
    web:
        build: 
            context: ./
        ports: 
            - "8000:8000"
            - "4200:4200"
        links:
            - "database"
            - "mcaas_db"
        depends_on: 
            - "database"
            - "mcaas_db"
        env_file:
            - ./env/container.env
        volumes:
            - type: bind
              source: ./sinwebapp
              target: /home/sinwebapp
            - type: bind
              source: ./frontend
              target: /home/frontend
        command: ["wait-for-it", "database:5432", "--","wait-for-it","mcaas_db:3306","--","bash","./init-app.sh","container"]

    database:
        image: "postgres:latest"
        ports: 
            - "5432:5432"
        env_file:
            - ./env/container.env

    mcaas_db: 
        image: "mysql:5.7"
        ports: 
            - "3306:3306"
        env_file:
            - ./env/container.env
