version: "3.8"
services:
    web:
        build: ./
        ports: 
            - "8000:8000"
        links:
            - "database"
        depends_on: 
            - "database"
        env_file:
            - ./env/container.env
        command: ["wait-for-it", "database:5432", "--","bash","./init-app.sh","container"]
    database:
        image: "postgres:latest"
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_DB=sinwebapp
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
