version: 2.1
# Use a package of configuration called an orb
jobs:
    build_job:
        docker:
            - image: python:3.7.7-slim-stretch
        steps:
            - checkout
            # install os libraries
            - run: apt-get update -y && apt-get install -y curl wget
            # install cf cli
            - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
                echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            # install node
            - run: curl -sL https://deb.nodesource.com/setup_14.x | bash - apt-get install -y nodejs
            # set up frontend for cloud
            - run: bash ./scripts/setup/setup-frontend-env.sh cloud
            # install dependencies and build frontend
            - run: bash ./scripts/build-frontend

workflows: 
    # Name the workflow "welcome"
    build: 
        # Run the welcome/run job in its own container
        jobs:
            - build_job