version: 2.1

executors:
    application-build:
        docker:
            - image: python:3.7.7-slim-stretch
jobs:
    build:
        executor: application-build
        steps:
            - checkout
            - run: 
                name: Install OS Dependencies
                command: apt-get update -y && apt-get install -y curl wget
            - run: 
                name: Download And Install CF CLI
                command: |
                    mkdir cf && cd cf
                    wget "https://packages.cloudfoundry.org/stable?release=debian64&source=github&version=v6"
                    dpkg -i $(ls)
                    cd ..
            - run: 
                name: Install Node
                command: curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs 
            - run: 
                name: Setup Frontend For Cloud Deployment
                command: bash ./scripts/setup/setup-frontend-env.sh cloud
            - run:
                name: Install Dependencies and Build Frontend
                command: npm install -g @angular/cli@8.2.0 && bash ./scripts/build-frontend.sh
            - run:
                name: Copy Initialization Scripts Into Application
                command: bash ./scripts/init-scripts.sh
        
    deploy_dev:    
        executor: application-build
        steps:
            - checkout
            - run:
                name: Push to CloudFoundry 
                command: |
                    echo $PATH
                    bash ./scripts/cc-cf-push.sh dev

workflows: 
    build_and_deploy: 
        jobs:
            - build:
                filters:
                    branches:
                        only: master
            - deploy_dev:
                requires: 
                    - build
                filters:
                    branches:
                        only: master