version: 2.1
# Use a package of configuration called an orb
jobs:
    build_job:
        docker:
            - image: python:3.7.7-slim-stretch
        steps:
            - checkout
            # install os libraries
            - run: apt-get update -y && apt-get install -y curl wget gnupg2
            # install cf cli
            - run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
            - run: mv cf /usr/local/bin
            # install node
            - run: curl -sL https://deb.nodesource.com/setup_14.x | bash - apt-get install -y nodejs
            # set up frontend for cloud
            - run: bash ./scripts/setup/setup-frontend-env.sh cloud
            # install dependencies and build frontend
            - run: bash ./scripts/build-frontend

workflows: 
    # Name the workflow "welcome"
    build: 
        # Run the welcome/run job in its own container
        jobs:
            - build_job