version: 2.1

executors:
    application-build:
        docker:
            - image: python:3.7.7-slim-stretch
        working_directory: /home/

jobs:
    build:
        executor: application-build
        steps:
            - checkout
            - run: 
                name: Install OS Dependencies
                command: apt-get update -y && apt-get install -y curl
            - run:
                name: Clean Application
                command: bash ./scripts/clean-app.sh
            - run: 
                name: Download And Install Node
                command: curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs 
            - run: 
                name: Setup Frontend For Cloud Deployment
                command: bash ./scripts/setup/setup-frontend-env.sh cloud
            - run:
                name: Install Dependencies And Build Frontend
                command: npm install -g @angular/cli@8.2.0 && bash ./scripts/build-frontend.sh
            - run:
                name: Install Python Requirements
                command: pip install -r ./sinwebapp/requirements.txt
            - run:
                name: Ensure Migrations Are Up To Date
                command: bash ./scripts/init-migrations.sh container
            - run:
                name: Copy Initialization Scripts Into Application
                command: bash ./scripts/init-scripts.sh 
            - persist_to_workspace: 
                root: ./sinwebapp/
                paths: 
                    - ./api/migrations/
                    - ./authentication/migrations/
                    - ./static/
                    - ./util/
                    - ./init-app.sh

    deploy_dev:    
        executor: application-build
        steps:
            - checkout
            - attach_workspace:
                at: /home/sinwebapp/
            - run: 
                name: Install OS Dependencies
                command: apt-get update -y && apt-get install -y wget
            - run: 
                name: Download And Install CF CLI
                command: |
                    mkdir cf && cd cf
                    wget "https://packages.cloudfoundry.org/stable?release=debian64&source=github&version=v6"
                    dpkg -i $(ls)
            - run:
                name: Push to CloudFoundry 
                command: |
                    bash ./scripts/cc-cf-push.sh dev

workflows: 
    build_and_deploy: 
        jobs:
            - build:
                filters:
                    branches:
                        only: master
            - deploy_dev:
                requires: 
                    - build
                filters:
                    branches:
                        only: master